libbitcoin/libbitcoin-blockchain

tools/stealth_db.cpp

Make stealth_db output more improved.

improve stealth_db output.

---

src/validate.cpp

encode_hex() -> encode_hash()

---

tools/initchain.cpp

- Make initchain more consistent with bitcoin_server given the

---

Makefile.am
builds/msvc/vs2013/libbitcoin-blockchain/libbitcoin-blockchain.vcxproj
builds/msvc/vs2013/libbitcoin-blockchain/libbitcoin-blockchain.vcxproj.filters
include/bitcoin/blockchain.hpp
include/bitcoin/blockchain/blockchain.hpp
include/bitcoin/blockchain/checkpoints.hpp
include/bitcoin/blockchain/fetch_block.hpp
include/bitcoin/blockchain/fetch_block_locator.hpp
include/bitcoin/blockchain/implementation/blockchain_impl.hpp
include/bitcoin/blockchain/organizer.hpp
include/bitcoin/blockchain/orphans_pool.hpp
include/bitcoin/blockchain/transaction_pool.hpp
include/bitcoin/blockchain/validate_transaction.hpp
src/blockchain.cpp
src/checkpoints.cpp
src/database/mman-win32/mman.c
src/database/mmfile.cpp
src/database/record_allocator.cpp
src/database/spend_database.cpp
src/db_interface.cpp
src/fetch_block.cpp
src/fetch_block_locator.cpp
src/implementation/blockchain_impl.cpp
src/implementation/organizer_impl.cpp
src/implementation/validate_block_impl.cpp
src/organizer.cpp
src/orphans_pool.cpp
src/transaction_pool.cpp
src/validate_block.cpp
src/validate_transaction.cpp

Changes include:
* throw when checkpoint is violated
* throw if disk error (like full)
* update logging with more detail
* refactor for class-per-file
* use atomic member flags
* make consistent use of auto and const
* fix lambda that was not kept in scope
* remove unnecessary copying

Various fixes and refactoring in support of sync stall fix.

---

src/validate_block.cpp

This patch is so simple I'm not sure what could be breaking the travis builds.  I made it even simpler to try again.  If this fails to build on some platforms again, I will need a better understanding of what the build system is doing that can cause this breakage.  If it applies cleanly, please test :-)
This should be linked to https://github.com/libbitcoin/libbitcoin-server/issues/51 because it's the fix for it (not sure how to link issues either at this point).

Testnet validation bug fix (sync stop at block #4032)

---

include/bitcoin/blockchain/impl/htdb_record.ipp
include/bitcoin/blockchain/impl/htdb_slab.ipp

https://github.com/libbitcoin/libbitcoin-blockchain/issues/96#issuecomment-148249288

Patch blockchain non-graceful read failure during write.

---

include/bitcoin/blockchain/impl/htdb_record.ipp
include/bitcoin/blockchain/impl/htdb_slab.ipp

Simple fix that resolves a master build error.

---

include/bitcoin/blockchain/impl/htdb_record.ipp
include/bitcoin/blockchain/impl/htdb_slab.ipp

Simple fix that resolves a version2 build error.

---

install.sh
src/interface/block_chain.cpp
src/interface/block_fetcher.cpp
src/pools/orphan_pool.cpp
src/pools/transaction_pool.cpp
src/pools/transaction_pool_index.cpp
src/validation/fork.cpp
src/validation/populate_block.cpp
src/validation/validate_block.cpp
src/validation/validate_transaction.cpp
test/fork.cpp
test/transaction_pool.cpp

...for chain and message namespace types. Additionally address warnings.

Field to property conversion

---

install.sh
src/interface/block_chain.cpp
src/interface/block_fetcher.cpp

Addresses libbitcoin/libbitcoin#530

Remove transaction count from header.

---

src/validation/fork.cpp
src/validation/populate_block.cpp

Updates build break due to libbitcoin commit https://github.com/libbitcoin/libbitcoin/commit/05cec5f05f0394402c2e8bdff49cfb3dce9da27e
Breakage noted here: https://github.com/thecodefactory/libbitcoin/commit/05cec5f05f0394402c2e8bdff49cfb3dce9da27e

Updates build break due to libbitcoin update

---

include/bitcoin/blockchain/interface/block_chain.hpp
include/bitcoin/blockchain/interface/fast_chain.hpp
include/bitcoin/blockchain/interface/safe_chain.hpp
include/bitcoin/blockchain/pools/block_organizer.hpp
include/bitcoin/blockchain/pools/transaction_organizer.hpp
include/bitcoin/blockchain/pools/transaction_pool.hpp
src/interface/block_chain.cpp
src/pools/block_organizer.cpp
src/pools/transaction_organizer.cpp
src/pools/transaction_pool.cpp
src/validate/validate_block.cpp
src/validate/validate_transaction.cpp
test/block_chain.cpp

Fortify and simplify locking, stub in tx orgzr, update tests, comments.

---

include/bitcoin/blockchain/interface/block_chain.hpp
include/bitcoin/blockchain/interface/fast_chain.hpp
include/bitcoin/blockchain/pools/branch.hpp
include/bitcoin/blockchain/populate/populate_chain_state.hpp
include/bitcoin/blockchain/settings.hpp
src/interface/block_chain.cpp
src/organizers/block_organizer.cpp
src/pools/block_pool.cpp
src/pools/branch.cpp
src/populate/populate_base.cpp
src/populate/populate_block.cpp
src/populate/populate_chain_state.cpp
src/settings.cpp
src/validate/validate_input.cpp
test/block_chain.cpp

Add median time past caching, settings, optimizations.

---

README.md

I matched the doc structure from `libbitcoin`. I can adjust, if desired.

Add Homebrew installation step

---

src/pools/block_organizer.cpp
src/pools/transaction_organizer.cpp

https://github.com/libbitcoin/libbitcoin-blockchain/issues/417

Fix organizer stop guards.

---

include/bitcoin/blockchain/interface/block_chain.hpp
include/bitcoin/blockchain/interface/fast_chain.hpp
src/interface/block_chain.cpp
src/pools/header_pool.cpp
src/populate/populate_block.cpp
src/populate/populate_header.cpp
src/populate/populate_transaction.cpp
src/validate/validate_block.cpp

This depends on database pull request.

Populate median_time_past, fix set_top_valid_candidate_state, style.

---

src/interface/block_chain.cpp

Thanks @JasonCoombs, see: https://github.com/libbitcoin/libbitcoin-blockchain/pull/457

Stop organizers outside of validation critical section.

---

include/bitcoin/blockchain/pools/header_branch.hpp
src/interface/block_chain.cpp
src/organizers/block_organizer.cpp
src/organizers/header_organizer.cpp
src/pools/header_branch.cpp
src/pools/header_pool.cpp
src/populate/populate_header.cpp
test/header_branch.cpp
test/header_pool.cpp

This is a work in progress, there are outstanding issues with header sync.

 Fix get_work and header population, comments.

---

src/interface/block_chain.cpp

Ref: libbitcoin/libbitcoin-blockchain#498

Switch to checking for cataloged, instead of existed

---

src/interface/block_chain.cpp

Requires https://github.com/libbitcoin/libbitcoin-database/pull/275

Update address database accessor to payment database (renamed).

---

include/bitcoin/blockchain/interface/block_chain.hpp
src/interface/block_chain.cpp

This will fail until https://github.com/libbitcoin/libbitcoin-database/pull/283 is merged.

Bury catalog call in database call to candidate.
